### ISSUE TITLE
dropping include support?

### ISSUE THREAD

**Issue by evangraan** [hetznerZA/jsender#7]
Ehm... you guys have just broken a lot of stuff for me. Why would you not want include support? Its one of the *major* values of the jsender gem?

Please fix.

**Comment by daneb** [comment]
Hi @evangraan 

There are 2 recommendations:
1. Peg your gem to version 0.2.2 (which supports include). This is why it was a major version bump so it would not have affected people who were using semantic versioning. This is a best practice and would have prevented you from being affected.
2. Use the latest (1.0.0) remove include, and just change "self." to "Jsender."

HTH

**Comment by evangraan** [comment]
Yes, of course. I've already done 1) But take not that everyone everywhere that prefer includes now is either forced to abandon it or to not benefit from future updates. Not cool.

2) shows how you have lost the value of include.

My suggestion is to fix release 1 by supporting include. This will be to your benefit. I'm sorted for my purposes though, so I'm checking out of this one.

**Comment by daneb** [comment]
@evangraan good point, sold and done.

One more thing to be aware of 'fail' (not failure) was removed due to it overriding the Kernel.fail method. Please check git log for 1.0.0 when the change took place if seeking further details.

**Comment by evangraan** [comment]
Please yank the 1.0.0 gem...

**Comment by daneb** [comment]
Done!
